
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1A209C7199142DBDA022AF67E371278E'
    
_lr_action_items = {'LBRACE':([5,],[6,]),'RPAREN':([4,],[5,]),'NAME':([6,7,10,11,15,17,18,21,22,31,35,37,38,39,],[13,13,13,20,26,-14,29,13,36,41,42,-6,-7,26,]),'SEMICOLON':([8,12,20,24,25,26,27,28,29,30,32,33,34,36,41,42,43,44,],[17,-16,-12,37,38,-13,-9,-11,-20,-23,-22,-15,-18,-19,-21,-17,-8,-10,]),'INT':([6,7,10,17,37,38,],[15,15,15,-14,-6,-7,]),'VOID':([0,],[1,]),'ASTERISK':([6,7,10,15,17,18,21,22,37,38,40,],[11,11,11,11,-14,11,11,11,-6,-7,11,]),'EQUAL':([9,13,20,],[18,22,-12,]),'RBRACE':([7,10,14,16,17,19,37,38,],[-2,-3,23,-4,-14,-5,-6,-7,]),'NUMBER':([18,],[30,]),'COMMA':([12,20,26,27,28,29,30,32,34,36,41,42,],[21,-12,-13,39,40,-20,-23,-22,-18,-19,-21,-17,]),'LPAREN':([3,],[4,]),'AMPERSAND':([18,22,],[31,35,]),'MAIN':([1,],[3,]),'$end':([2,23,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statlist':([15,39,],[24,43,]),'pointerlist':([15,40,],[25,44,]),'function_content':([6,7,10,],[14,16,19,]),'singleAssignment':([6,7,10,21,],[12,12,12,12,]),'assignment_statement':([6,7,10,],[10,10,10,]),'statvar':([15,39,],[27,27,]),'program':([0,],[2,]),'declaration':([6,7,10,],[7,7,7,]),'assignmentlist':([6,7,10,21,],[8,8,8,33,]),'pointer':([6,7,10,15,18,21,22,40,],[9,9,9,28,32,9,34,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> VOID MAIN LPAREN RPAREN LBRACE function_content RBRACE','program',7,'p_program','150050076-150050096.py',92),
  ('function_content -> declaration','function_content',1,'p_function_content','150050076-150050096.py',98),
  ('function_content -> assignment_statement','function_content',1,'p_function_content','150050076-150050096.py',99),
  ('function_content -> declaration function_content','function_content',2,'p_function_content','150050076-150050096.py',100),
  ('function_content -> assignment_statement function_content','function_content',2,'p_function_content','150050076-150050096.py',101),
  ('declaration -> INT statlist SEMICOLON','declaration',3,'p_declaration','150050076-150050096.py',105),
  ('declaration -> INT pointerlist SEMICOLON','declaration',3,'p_declaration1','150050076-150050096.py',109),
  ('statlist -> statvar COMMA statlist','statlist',3,'p_statlist','150050076-150050096.py',114),
  ('statlist -> statvar','statlist',1,'p_statlist1','150050076-150050096.py',120),
  ('pointerlist -> pointer COMMA pointerlist','pointerlist',3,'p_pointerlist','150050076-150050096.py',127),
  ('pointerlist -> pointer','pointerlist',1,'p_pointerlist1','150050076-150050096.py',132),
  ('pointer -> ASTERISK NAME','pointer',2,'p_pointer','150050076-150050096.py',136),
  ('statvar -> NAME','statvar',1,'p_statvar','150050076-150050096.py',141),
  ('assignment_statement -> assignmentlist SEMICOLON','assignment_statement',2,'p_assignment_statement','150050076-150050096.py',146),
  ('assignmentlist -> singleAssignment COMMA assignmentlist','assignmentlist',3,'p_assignmentlist','150050076-150050096.py',149),
  ('assignmentlist -> singleAssignment','assignmentlist',1,'p_assignmentlist','150050076-150050096.py',150),
  ('singleAssignment -> NAME EQUAL AMPERSAND NAME','singleAssignment',4,'p_singleAssignment','150050076-150050096.py',154),
  ('singleAssignment -> NAME EQUAL pointer','singleAssignment',3,'p_singleAssignment','150050076-150050096.py',155),
  ('singleAssignment -> NAME EQUAL NAME','singleAssignment',3,'p_singleAssignment','150050076-150050096.py',156),
  ('singleAssignment -> pointer EQUAL NAME','singleAssignment',3,'p_singleAssignment1','150050076-150050096.py',162),
  ('singleAssignment -> pointer EQUAL AMPERSAND NAME','singleAssignment',4,'p_singleAssignment1','150050076-150050096.py',163),
  ('singleAssignment -> pointer EQUAL pointer','singleAssignment',3,'p_singleAssignment1','150050076-150050096.py',164),
  ('singleAssignment -> pointer EQUAL NUMBER','singleAssignment',3,'p_singleAssignment1','150050076-150050096.py',165),
]
